#
# Copyright (c) 2022 Amazon.com, Inc. or its affiliates.  All rights reserved.
#
# PROPRIETARY/CONFIDENTIAL.  USE IS SUBJECT TO LICENSE TERMS.
#
schema-version = 1

[package]
title = "Basic UI React Native Application for project rnlconfapp"
version = "0.1.0"
id = "com.amazondeveloper.rnlconfapp"

[components]
[[components.interactive]]
id = "com.amazondeveloper.rnlconfapp.main"
runtime-module = "/com.amazon.kepler.keplerscript.runtime.loader_2@IKeplerScript_2_0"
launch-type = "singleton"
categories = ["com.amazon.category.main"]

[wants]
# WebView services
[[wants.service]]
id = "com.amazon.webview.renderer_service"

# Keyboard support for WebView
[[wants.service]]
id = "com.amazon.inputmethod.service"

# UCC service for accessibility support
[[wants.service]]
id = "com.amazon.kepler.ucc.publisher"

# Core media services
[[wants.service]]
id = "com.amazon.mediametrics.service"
[[wants.service]]
id = "com.amazon.media.server"
[[wants.service]]
id = "com.amazon.gipc.uuid.*"
[[wants.service]]
id = "com.amazon.media.playersession.service"

# Media processing
[[wants.service]]
id = "com.amazon.mediabuffer.service"
[[wants.service]]
id = "com.amazon.mediatransform.service"

# Audio services
[[wants.service]]
id = "com.amazon.audio.stream"
[[wants.service]]
id = "com.amazon.audio.control"
[[wants.service]]
id = "com.amazon.audio.system"

# Accessibility (for captions)
[[wants.privilege]]
id = "com.amazon.devconf.privilege.accessibility"

[offers]
[[offers.service]]
id = "com.amazon.gipc.uuid.*"
